/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vUzoe1HlGco
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "../shadcn-ui/input"
import { Button } from "../shadcn-ui/button"
import { useState } from "react";
import Global from "../../Utils/Global";
import { quantum } from 'ldrs'
import RecommendedBike from "../../Pages/Home/RecommendedBike"

export default function AIchat() {

  quantum.register()
  const [prompt_text, setPromptText] = useState("");
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState([]);

  const handleInputChange = (e) => {
    setPromptText(e.target.value);
  }

  const handleGenerateClick = async () => {
    try {
      if (prompt_text != "")
        setLoading(true);
      const res = await Global.httpPost('/bikes/recommend', {
        prompt: prompt_text
      })
      console.log(res)
      setLoading(false);
      setData(res);
    } catch (error) {
      console.log(error);
    }
  }


  return (
    (<div
      className="flex flex-col items-center justify-center font-dm-sans  min-h-screen bg-background text-foreground">
      <div className=" w-full space-y-6 px-4">
        <div className="text-center space-y-2 ">
          <h1 className="text-4xl font-bold text-green-900">Get a new E-Bike Today!</h1>
          <p className="text-muted-foreground">with our smart AI Assitant.</p>
        </div>
        <div className="space-y-2 flex justify-center flex-col items-center">
          <div className="w-1/3 gap-y-5 flex flex-col">
            <Input
              type="text"
              placeholder="Describe the topic you'd like the AI to write about..."
              className="w-full"
              value={prompt_text}
              onChange={handleInputChange} />
            <Button className="w-full bg-green-800 hover:bg-green-900" onClick={handleGenerateClick}>Generate</Button>
          </div>
          {loading && (
            <div className="flex items-center justify-center mt-20">
              <l-quantum
                size="45"
                speed="1.75"
                color="black"
              ></l-quantum>
            </div>)}
          {!loading && (
            <div className="grid grid-cols-3 items-center w-full h-full gap-28 mt-52 p-20">
              {data.map((data) => (
                <RecommendedBike key={data.brandId} image={data.image} name={data.name} price={data.price} topSpeed={data.topSpeed} range={data.range} chargingtime={data.chargingTime} />
              ))}
            </div>
          )}
        </div>
      </div>
    </div>)
  );
}
